/**
 * Codegen for translatable DYNAMIC strings (Bucket 1: finite, enumerable lists).
 *
 * Why this exists:
 *   Canva translates strings by running `formatjs extract` over our SOURCE CODE at
 *   build time, then translating the resulting messages_en.json. Values that live in
 *   MySQL (metric titles, timeframe labels, geo-type labels) are never literals in our
 *   source, so the extractor can't see them and Canva never translates them.
 *
 *   This script pulls the finite catalog from the live API and writes those values out
 *   as `defineMessage` literals into a generated .ts file. Once committed, the normal
 *   `npm run extract` picks them up and Canva translates them like any other UI string.
 *   At runtime the app looks up the translation by the DB id (see app.tsx).
 *
 * When to re-run:
 *   Only when the catalog changes (a metric/timeframe/geo-type is added or renamed).
 *   Run it, commit the regenerated file, rebuild, and resubmit the app to Canva.
 *
 * Usage:
 *   npx ts-node ./scripts/i18n/gen-dynamic-messages.ts
 */

import { writeFileSync, mkdirSync } from "fs";
import { dirname, resolve } from "path";

const API = "https://data.indianarealtors.com/api/canva";

// Only these geo types are shown in the app (mirror of ALLOWED_GEO_TYPES in app.tsx).
// We enumerate vizzes for one geo of each type so we capture every metric id the app
// could ever display, since the catalog can differ by geo type.
const ALLOWED_GEO_TYPES = ["County", "ZIP Code", "State", "Township"];

const OUT_PATH = resolve(
  __dirname,
  "../../src/intents/design_editor/generated/dynamic-messages.ts",
);

type Item = {
  id: string | number;
  name?: string;
  title?: string;
  subtitle?: string;
  label?: string;
};

async function getJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} -> ${res.status}`);
  return (await res.json()) as T;
}

function esc(s: string): string {
  return JSON.stringify(s);
}

async function main() {
  // --- geo types ---
  const geoTypesResp = await getJson<{ items: string[] }>(`${API}/geo_types`);
  const geoTypes = geoTypesResp.items.filter((t) =>
    ALLOWED_GEO_TYPES.some((a) => a.toLowerCase() === t.toLowerCase().trim()),
  );

  // --- timespans ---
  const timespansResp = await getJson<{ items: Item[] }>(`${API}/timespans`);
  const timespans = timespansResp.items;

  // --- vizzes: union across one geo per allowed type, timespan=all ---
  const vizById = new Map<string, { title: string; subtitle?: string }>();
  for (const type of geoTypes) {
    const geos = await getJson<{ items: Item[] }>(
      `${API}/geos?type=${encodeURIComponent(type)}`,
    );
    const firstGeo = geos.items[0];
    if (!firstGeo) continue;

    const vizzes = await getJson<{ items: Item[] }>(
      `${API}/vizzes?geo_id=${encodeURIComponent(String(firstGeo.id))}&timespan=all`,
    );
    for (const v of vizzes.items) {
      const id = String(v.id);
      const title = (v.title || v.name || "").trim();
      const subtitle = (v.subtitle || "").trim();
      if (!title) continue;
      // First write wins; ids are stable across geo types.
      if (!vizById.has(id)) {
        vizById.set(id, { title, subtitle: subtitle || undefined });
      }
    }
  }

  const sortedVizIds = [...vizById.keys()].sort(
    (a, b) => Number(a) - Number(b),
  );

  // --- emit ---
  const lines: string[] = [];
  lines.push(
    "/* eslint-disable */",
    "// AUTO-GENERATED by scripts/i18n/gen-dynamic-messages.ts — DO NOT EDIT BY HAND.",
    "// Re-run `npx ts-node ./scripts/i18n/gen-dynamic-messages.ts` when the catalog changes,",
    "// then commit, rebuild, and resubmit the app to Canva so the new strings get translated.",
    'import { defineMessage } from "react-intl";',
    'import type { MessageDescriptor } from "react-intl";',
    "",
    "// Geo type label, keyed by the raw API value (which is also the API request param).",
    "export const GEO_TYPE_MESSAGES: Record<string, MessageDescriptor> = {",
  );
  for (const t of geoTypes) {
    lines.push(
      `  ${esc(t)}: defineMessage({ defaultMessage: ${esc(t)}, description: "Geo type label" }),`,
    );
  }
  lines.push("};", "");

  lines.push(
    "// Timeframe label, keyed by timespan id.",
    "export const TIMESPAN_MESSAGES: Record<string, MessageDescriptor> = {",
  );
  for (const t of timespans) {
    const label = (t.label || String(t.id)).trim();
    lines.push(
      `  ${esc(String(t.id))}: defineMessage({ defaultMessage: ${esc(label)}, description: "Timeframe label" }),`,
    );
  }
  lines.push("};", "");

  lines.push(
    "// Metric title + subtitle, keyed by viz id.",
    "export const VIZ_MESSAGES: Record<string, { title: MessageDescriptor; subtitle?: MessageDescriptor }> = {",
  );
  for (const id of sortedVizIds) {
    const { title, subtitle } = vizById.get(id)!;
    const parts = [
      `title: defineMessage({ defaultMessage: ${esc(title)}, description: "Metric title" })`,
    ];
    if (subtitle) {
      parts.push(
        `subtitle: defineMessage({ defaultMessage: ${esc(subtitle)}, description: "Metric subtitle" })`,
      );
    }
    lines.push(`  ${esc(id)}: { ${parts.join(", ")} },`);
  }
  lines.push("};", "");

  const out = lines.join("\n");
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, out, "utf8");

  // eslint-disable-next-line no-console
  console.log(
    `Wrote ${OUT_PATH}\n  geo types: ${geoTypes.length}\n  timespans: ${timespans.length}\n  vizzes: ${sortedVizIds.length}`,
  );
}

main().catch((e) => {
  // eslint-disable-next-line no-console
  console.error(e);
  process.exit(1);
});
